project: 
  type: website
  output-dir: docs

website:
  title: "ViruScan"
  navbar:
    logo: altapplogo.png
    left:
      - text: "About ViruScan"
        file: about.qmd
      - text: "Dashboards"
        menu:
          - text: "COVID-19"
            file: Dashboards/COVID19.qmd
          - text: "Influenza"
            file: Dashboards/Influenza.qmd
          - text: "Rhinovirus (Common Cold)"
            file: Dashboards/Rhinovirus.qmd
          - text: "Respiratory Syncytial Virus (RSV)"
            file: Dashboards/RSV.qmd
      - text: "Testing & Vaccination Sites"
        menu:
          - text: "Testing"
            file: Testing_Vaccination/Testing.qmd
          - text: "Vaccination"
            file: Testing_Vaccination/Vaccination.qmd
    right:
      - href: https://prepare.uga.edu/uga-safe/
        text: "<img src='UGASafelogo.png' alt='UGA Safe Logo' style='height:30px; width:auto; vertical-align:middle;'>"

  page-footer:
    center:
      - text: "<img src='footer/combined.png' alt='' style='height:100px; width:auto; vertical-align:middle;'>"
      - href: https://healthcenter.uga.edu/
        text: "University of Georgia Health Center"
      - href: https://prepare.uga.edu/uga-safe/
        text: "UGA Safe"
      - href: about.html
        text: "About ViruScan"
      - href: Dashboards/COVID19.html
        text: "COVID-19 Dashboard"
      - href: Dashboards/Influenza.html
        text: "Influenza Dashboard"
      - href: Dashboards/Rhinovirus.html
        text: "Common Cold Dashboard"
      - href: Dashboards/RSV.html
        text: "RSV Dashboard"
      - href: Testing_Vaccination/Testing.html
        text: "Testing"
      - href: Testing_Vaccination/Vaccination.html
        text: "Vaccination"

format:
  html:
    theme: yeti
    highlight: zenburn
    css: styles.css
    toc: false

